default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= Rails.application.credentials.dig(:database, :host) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>

development:
  <<: *default
  database: rrr_service_dev

test:
  <<: *default
  database: rrr_service_test

production:
  <<: *default
  database: rrr_service_prod

